# Site settings
title: "Comple Trip - 1박 2일"
description: "각 도별 연인들이 1박 2일로 놀러 가기 좋은 여행지"
baseurl: ""
url: "http://traveltrip.github.io"

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments
paginate: 3

# Links
links:
  - title: "경기도, 강원도"
    url: /about
  - title: "충청도"
    url: http://twitter.com/alixedi
  - title: "전라도"
    url: http://github.com/alixedi
  - title: "경상도"
    url: http://www.daum.net

